apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "customer-backend.fullname" . }}
  labels:
    {{- include "customer-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "customer-backend.name" . }}
  template:
    metadata:
      labels:
        {{- include "customer-backend.labels" . | nindent 8 }}
    spec:
      containers:
        - name: customer-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
