{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "customer-backend.fullname" . }}
spec:
  to:
    kind: Service
    name: {{ include "customer-backend.fullname" . }}
  port:
    targetPort: 8080
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: edge
  {{- end }}
{{- end }}
